### ISSUE TITLE
scraper error, just reporting, not investigated yet.

### ISSUE THREAD

**Issue by rkiddy** [codeforsanjose/open-disclosure#37]
Here is what I did to get here.
I will investigated. Just wanted to get this in.
thanx - ray

`% virtualenv env

% source env/bin/activate
(env) % 

(env) % python3 -m pip install chromedriver_binary

(env) % python3 -m pip install webdriver-manager

(env) % python3 -m pip install selenium         

(env) % python ./scraper.py    
        
data/Ballot_Measure
 
[WDM] - Current google-chrome version 83.0.4103
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_mac64.zip
[WDM] - Unpack archive /Users/ray/.wdm/drivers/chromedriver/83.0.4103.39/mac64/chromedriver.zip

Traceback (most recent call last):
  File "./scraper.py", line 222, in <module>
    s.scrape()
  File "./scraper.py", line 207, in scrape
    self.website.closeErrorDialog(self.driver)
  File "./scraper.py", line 90, in closeErrorDialog
    driver.find_element_by_id(self.ERROR_DIALOG_BUTTON_ID).click()
  File "/Users/ray/Projects/open-disclosure/data_pipeline/scraper/env/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/ray/Projects/open-disclosure/data_pipeline/scraper/env/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "/Users/ray/Projects/open-disclosure/data_pipeline/scraper/env/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/ray/Projects/open-disclosure/data_pipeline/scraper/env/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=83.0.4103.61)
`

**Comment by rkiddy** [comment]
![Uploading Screen Shot 2020-06-03 at 2.23.27 PM.png…]()

**Comment by rkiddy** [comment]
I re-ran the scraper. The third time I ran it, it got all of the way through.
